### ISSUE TITLE
welcomer not working correctly

### ISSUE THREAD

**Issue by XPower7125** [Baracchino-Della-Scuola/Bot#10]
![image](https://user-images.githubusercontent.com/64551044/164884978-f4ef92ca-ed0b-4a77-bc50-7fee061f3733.png)
there are some problems with images

**Comment by StarNumber12046** [comment]
Thatybecause the VM instance @ railway does not correctly launch the API request with the env variable, our pi-hosted copy works anyway

**Comment by StarNumber12046** [comment]
it is fixed
