### ISSUE TITLE
.download command not working

### ISSUE THREAD

**Issue by XPower7125** [Baracchino-Della-Scuola/Bot#24]
the .download command doesn't work correctly: even if the file name is correct it will give an error: "file not found, please try with a different file".
![image](https://user-images.githubusercontent.com/64551044/194281378-fc257d24-1cdc-48d6-a4cd-c31c9879eca7.png)

**Comment by StarNumber12046** [comment]
We'll investigate

**Comment by StarNumber12046** [comment]
Fixed in latest commit, it was a path dir, tell me if it reappears!
