### ISSUE TITLE
posso rifarlo in javascript?

### ISSUE THREAD

**Issue by Xenon-YT** [Baracchino-Della-Scuola/Bot#6]
**dico solo questo**
la libreria python di discord **non sarà più supportata** dalle nuove versioni delle API di discord
invece discord.js v13 sarà ancora supportato da discord
quindi si cambi il linguaggio
(e magari accetti le mie pull request)
Xenon-YT

**Comment by StarNumber12046** [comment]
Usiamo una fork (enhanced discord.py) ancora supportata quindi per ora penso che lo terremo così

**Comment by Xenon-YT** [comment]
End of life for discord.js version 11 and 12 (e discord.py):
• Discord will decommission (shut off) API version 6 and 7 on April 30, 2022. https://github.com/discord/discord-api-docs/discussions/4510
• Version 11 and 12 of discord.js will stop working then (note that we only provide support for version 13 on our support server)
• If you haven't updated to v13 already, now is the time! https://discordjs.guide/additional-info/changes-in-v13.html 
si prepari

**Comment by StarNumber12046** [comment]
enhanced discord.py usa la nuova API e supporta slash commands e components

**Comment by Xenon-YT** [comment]
ah
